/**
 * App Branding & Service Abstraction
 * All third-party services are abstracted with custom branded names
 */

export const APP_BRANDING = {
  // Main App Info
  appName: "AI Chef",
  appFullName: "AI Chef Meal Planner",
  tagline: "Your Personal AI Cooking Assistant",
  
  // Custom Service Names (abstracts third-party APIs)
  ingredientSearch: {
    name: "ChefSearch™",
    tagline: "Powered by our global ingredient database",
    description: "Access millions of ingredients from around the world",
  },
  
  aiRecipeGenerator: {
    name: "SmartRecipe AI™",
    tagline: "AI-powered personalized recipes",
    description: "Intelligent meal planning tailored to your needs",
  },
  
  nutritionData: {
    name: "NutriTrack™",
    tagline: "Comprehensive nutritional insights",
    description: "Accurate nutrition data for every ingredient",
  },
  
  pantrySystem: {
    name: "SmartPantry™",
    tagline: "Intelligent ingredient management",
    description: "Track and manage your kitchen inventory",
  },
};

// Feature descriptions (abstracted from implementation details)
export const FEATURE_DESCRIPTIONS = {
  ingredientSearch: "Search millions of ingredients with our proprietary ChefSearch™ technology",
  aiRecipes: "Generate personalized recipes using SmartRecipe AI™",
  nutritionTracking: "Track nutrition with NutriTrack™ comprehensive database",
  pantryManagement: "Manage your kitchen with SmartPantry™ intelligent system",
};

// UI Text (no mention of third-party services)
export const UI_TEXT = {
  pantry: {
    searchPlaceholder: "Search millions of ingredients...",
    searchPoweredBy: "Powered by ChefSearch™",
    searchDescription: "Access our comprehensive global ingredient database",
    noResults: "No results found in our database",
    addCustom: "Add as custom ingredient",
  },
  
  mealPlanning: {
    generatingMessage: "SmartRecipe AI™ is creating your personalized meal plan...",
    generatedBy: "Generated by SmartRecipe AI™",
    nutritionPoweredBy: "Nutrition data by NutriTrack™",
  },
  
  dashboard: {
    welcome: "Welcome to AI Chef",
    subtitle: "Your intelligent cooking companion",
  },
};

// Footer/About text (generic, professional)
export const ABOUT_TEXT = {
  short: "AI Chef uses advanced technology to provide personalized meal planning and nutrition tracking.",
  
  long: `AI Chef is your personal cooking assistant powered by cutting-edge artificial intelligence. 
  Our proprietary systems - ChefSearch™, SmartRecipe AI™, and NutriTrack™ - work together to provide 
  you with personalized meal plans, comprehensive ingredient databases, and accurate nutritional insights.`,
  
  technology: "Built with state-of-the-art AI and data aggregation technology",
  
  dataSource: "Our ingredient database aggregates information from trusted global sources",
};
